Coderfactory_Notes/Week9/uploader/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :gifts
  root 'gifts#index'
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'add_to_cart', to: 'carts#add_to_cart'
  get 'empty_cart', to: 'carts#empty_cart'
end

Coderfactory_Notes/Week9/uploader/app/models/gift.rb
class Gift < ApplicationRecord

  mount_uploader :picture, GiftPictureUploader

end

Coderfactory_Notes/Week9/uploader/app/models/product.rb
class Product < ApplicationRecord

  validates :name,  presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than: 0 }
 
  def price_in_cents
    (price * 100).to_i
  end
  
end

Coderfactory_Notes/Week9/uploader/app/controllers/carts_controller.rb
class CartsController < ApplicationController

def add_to_cart
  @gift = Gift.find(params[:gift])
  session[:cart] = [] unless session[:cart]
  session[:cart] << @gift.id
  session[:total] = get_session_price(session[:cart])
  flash[:message] = "#{@gift.name} added to cart"
  redirect_to @gift
end

def empty_cart
  reset_session
  flash[:message] = "Cart emptied"
  redirect_to gifts_path
end

def get_session_price(array_of_products)
  total = 0.00
  array_of_products.each do |prod|
    x = Gift.find(prod)
    total += x.price.to_i
  end
  total * 10
end

end

Coderfactory_Notes/Week9/uploader/app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @all_products = session[:cart].map {|x| Gift.find(x)}
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

Coderfactory_Notes/Week9/uploader/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:picture, :name, :price)
    end
end

Coderfactory_Notes/Week9/uploader/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

Coderfactory_Notes/Week9/uploader/app/helpers/cart_helper.rb
module CartHelper
end

Coderfactory_Notes/Week9/uploader/app/helpers/gifts_helper.rb
module GiftsHelper
end

Coderfactory_Notes/Week9/uploader/app/helpers/products_helper.rb
module ProductsHelper
end

Coderfactory_Notes/Week9/uploader/app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

Coderfactory_Notes/Week9/uploader/app/views/charges/new.html.erb
<% @all_products.each do |product| %>
  <p>
    <%= product.name%>
    <%= image_tag(product.picture.url)%>
  </p>
<% end %>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= session[:total]%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= session[:total]*10 %>"
          data-locale="auto"></script>
<% end %>

Coderfactory_Notes/Week9/uploader/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to 'Gifts', gifts_path %>|<%= link_to "Checkout", new_charge_path %>|<%= link_to "Empty Cart", empty_cart_path %>
  <%= session[:total] if session[:total] %>
    <%= yield %>
  </body>
</html>

Coderfactory_Notes/Week9/uploader/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
  <%= link_to 'Gifts', gifts_path %>|<%= link_to "Checkout", new_charge_path %>|<%= link_to "Empty Cart", empty_cart_path %>
    <%= yield %>
  </body>
</html>