Coderfactory_Notes/Week7/instapic/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users do
    resources :profiles
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Coderfactory_Notes/Week7/instapic/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :tagged_user_relationships, class_name: 'PhotoTaggedUser'
end

Coderfactory_Notes/Week7/instapic/app/models/photo_tagged_user.rb
class PhotoTaggedUser < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

Coderfactory_Notes/Week7/instapic/app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :photos
  accepts_nested_attributes_for :profile
end

Coderfactory_Notes/Week7/instapic/app/models/user_follower_relationship.rb
class UserFollowerRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :follower
end

Coderfactory_Notes/Week7/instapic/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @photos = Photo.all
  end
end

Coderfactory_Notes/Week7/instapic/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_user, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :find_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
  end

  def show
    @params = params
  end

  def new
    @profile = Profile.new
  end

  def edit

  end

  def create
    @profile = Profile.create(profile_params)
    if @profile.save
      redirect_to @profile
    else
      render new
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_path
  end


  private

    def find_profile
      @profile = Profile.find(params[:id])
    end

    def find_user
      @user = User.find(params[:user_id])
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :phone, :user_id )
    end
end

Coderfactory_Notes/Week7/instapic/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @params = params
  end

  def new
    @user = User.new
  end

  def edit

  end

  def update
      if @user.update_attributes(user_params)
        # Handle a successful update.
        redirect_to users_path
      else
        render new_user_path
      end
    end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to @user
    else
      render new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end


  private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password_hash)
    end

end

Coderfactory_Notes/Week7/instapic/app/helpers/pages_helper.rb
module PagesHelper
end

Coderfactory_Notes/Week7/instapic/app/helpers/users_helper.rb
module UsersHelper
end

Coderfactory_Notes/Week7/instapic/app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :password_hash %><br>
    <%= f.text_field :password_hash %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

Coderfactory_Notes/Week7/instapic/app/views/users/edit.html.erb
<h1>Edit!</h1>

<%= render 'form' %>

Coderfactory_Notes/Week7/instapic/app/views/users/index.html.erb
<h1>Users Index</h1>
  <table>
    <thr>
      <td>Email</td>
      <td>Password</td>
      <td>Photos</td>
      <td>Links</td>
    </tr>
      <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.password_hash %></td>
      <td><%= user.photos.count %></td>
      <td>
        <%= link_to "Show", user_path(user) %>
        <%= link_to "Edit", edit_user_path(user) %>
        <%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "New", new_user_path %>

Coderfactory_Notes/Week7/instapic/app/views/users/new.html.erb
<h1>New!</h1>

<%= render 'form' %>

Coderfactory_Notes/Week7/instapic/app/views/users/show.html.erb
<h1>User Page</h1>
<%= @user.email %>
<%= @user.password_hash %>

<% @params.each do |k, v| %>
  <p>
    <%= k %>
    <%= v %>
  </p>
<% end %>

<%= link_to "New Profile", new_user_profile_path(@user) %>
<%= link_to "Profiles", user_profiles_path(@user) %>